import React from 'react';

import Header from './components/header/Header';
import { AppContextProvider } from './context/AppContext';

import './assets/global.css';

function App() {
  return (
    <AppContextProvider>
      <Header />
      <p>Lorem.</p>
      <p>Dolores!</p>
      <p>Numquam!</p>
      <p>Non.</p>
      <p>Aspernatur!</p>
      <p>Enim.</p>
      <p>Soluta.</p>
      <p>Laudantium.</p>
      <p>Sequi!</p>
      <p>Aspernatur?</p>
      <p>Quae?</p>
      <p>Illo.</p>
      <p>Repudiandae!</p>
      <p>Distinctio?</p>
      <p>Placeat!</p>
      <p>Et.</p>
      <p>Nihil?</p>
      <p>Impedit?</p>
      <p>Veniam.</p>
      <p>Voluptatem!</p>
      <p>Earum.</p>
      <p>Libero!</p>
      <p>Voluptatem!</p>
      <p>Explicabo.</p>
      <p>Assumenda.</p>
      <p>Nesciunt.</p>
      <p>Necessitatibus.</p>
      <p>Modi.</p>
      <p>Nemo.</p>
      <p>Maiores.</p>
      <p>Nulla!</p>
      <p>Tenetur?</p>
      <p>Asperiores?</p>
      <p>Corrupti?</p>
      <p>Ratione.</p>
      <p>In.</p>
      <p>Dolores?</p>
      <p>Laudantium.</p>
      <p>Dignissimos.</p>
      <p>Doloremque.</p>
      <p>Reprehenderit?</p>
      <p>Nemo.</p>
      <p>Nisi.</p>
      <p>Enim?</p>
      <p>Eius.</p>
      <p>Vel.</p>
      <p>Adipisci.</p>
      <p>Laborum!</p>
      <p>Assumenda!</p>
      <p>Magni!</p>
      <p>Dolorem.</p>
      <p>Repellat?</p>
      <p>Cumque.</p>
      <p>Dolorum.</p>
      <p>Odio.</p>
      <p>Hic.</p>
      <p>Natus?</p>
      <p>Sint?</p>
      <p>Repellat.</p>
      <p>Magni!</p>
      <p>Animi?</p>
      <p>Sit!</p>
      <p>Rem.</p>
      <p>Iusto?</p>
      <p>Iure.</p>
      <p>Molestiae.</p>
      <p>Voluptas?</p>
      <p>Architecto.</p>
      <p>Modi!</p>
      <p>Velit?</p>
      <p>Fugiat!</p>
      <p>Nulla!</p>
      <p>Quisquam!</p>
      <p>Qui?</p>
      <p>Doloremque?</p>
      <p>Officiis.</p>
      <p>Optio.</p>
      <p>Nemo?</p>
      <p>Delectus.</p>
      <p>Rerum!</p>
      <p>Consequuntur?</p>
      <p>Ut?</p>
      <p>Laudantium.</p>
      <p>Deserunt?</p>
      <p>Alias.</p>
      <p>Nulla!</p>
      <p>Quos.</p>
      <p>Dolorem!</p>
      <p>Eos.</p>
      <p>Veritatis!</p>
      <p>Esse!</p>
      <p>Magnam.</p>
      <p>Blanditiis?</p>
      <p>Facilis.</p>
      <p>Fuga.</p>
      <p>Magnam.</p>
      <p>Doloribus!</p>
      <p>Illum.</p>
      <p>Quod?</p>
      <p>Numquam?</p>
      <p>Labore.</p>
      <p>Dolore.</p>
      <p>Voluptatibus.</p>
      <p>Consectetur.</p>
      <p>Repudiandae.</p>
      <p>Repellendus.</p>
      <p>Eveniet.</p>
      <p>Repudiandae.</p>
      <p>Debitis.</p>
      <p>Quasi.</p>
      <p>Reprehenderit.</p>
      <p>Placeat.</p>
      <p>Quasi?</p>
      <p>Voluptatum.</p>
      <p>Ullam?</p>
      <p>Perferendis.</p>
      <p>Beatae!</p>
      <p>Est.</p>
      <p>Tempore.</p>
      <p>Beatae.</p>
      <p>Aliquid.</p>
      <p>Quos.</p>
      <p>Veritatis.</p>
      <p>Exercitationem!</p>
      <p>Impedit?</p>
      <p>Quasi!</p>
      <p>Vitae?</p>
      <p>Commodi?</p>
      <p>Vel.</p>
      <p>Eius?</p>
      <p>Facere.</p>
      <p>Repellendus.</p>
      <p>Fuga.</p>
      <p>Exercitationem.</p>
      <p>Perspiciatis.</p>
      <p>Id!</p>
      <p>Praesentium.</p>
      <p>Rem!</p>
      <p>Consequuntur!</p>
      <p>Quo.</p>
      <p>At!</p>
      <p>Quisquam?</p>
      <p>Veritatis.</p>
      <p>Accusamus.</p>
      <p>Possimus?</p>
      <p>Quas.</p>
      <p>Deleniti.</p>
      <p>Soluta.</p>
      <p>Soluta!</p>
      <p>Alias!</p>
      <p>Consectetur.</p>
      <p>Cupiditate!</p>
      <p>Tempora?</p>
      <p>Ea.</p>
      <p>Animi?</p>
      <p>Rerum!</p>
      <p>Impedit?</p>
      <p>Sapiente?</p>
      <p>Recusandae!</p>
      <p>Exercitationem?</p>
      <p>Inventore?</p>
      <p>Officia!</p>
      <p>Obcaecati!</p>
      <p>Voluptatum.</p>
      <p>Ad!</p>
      <p>Suscipit.</p>
      <p>Atque?</p>
      <p>Obcaecati.</p>
      <p>Explicabo!</p>
      <p>Similique!</p>
      <p>Commodi.</p>
      <p>Distinctio!</p>
      <p>Iure.</p>
      <p>Officiis!</p>
      <p>Aliquid?</p>
      <p>Ratione?</p>
      <p>Beatae?</p>
      <p>Voluptatibus?</p>
      <p>Laudantium?</p>
      <p>Nobis.</p>
      <p>Modi!</p>
      <p>Pariatur!</p>
      <p>Animi.</p>
      <p>Pariatur!</p>
      <p>Commodi.</p>
      <p>Voluptatem!</p>
      <p>Neque?</p>
      <p>Commodi?</p>
      <p>Molestiae!</p>
      <p>Rem.</p>
      <p>Non.</p>
      <p>Blanditiis!</p>
      <p>Alias.</p>
      <p>Odio?</p>
      <p>Corrupti.</p>
      <p>Voluptatibus.</p>
      <p>Amet.</p>
      <p>Tempora!</p>
      <p>Commodi.</p>
      <p>Quisquam!</p>
    </AppContextProvider>
  );
}

export default App;
